HCM/Models/Members.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ClubManagement.Models
{
    public class Members
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Họ tên")]
        public string FullName { get; set; }
        [Required]
        [Display(Name = "MSSV")]
        public string StudentNumber { get; set; }
        [Required]
        [Display(Name = "Mật khẩu")]
        //[StringLength(18, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        //[RegularExpression(@"^((?=.*[a-z])(?=.*[A-Z])(?=.*\d)).+$")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        [Display(Name = "SĐT")]
        [Phone]
        [Required]
        public string PhoneNumber { get; set; }
        [Display(Name="Trạng thái")]
        public bool IsAccecpt { get; set; }
        [Display(Name = "CLB")]
        public int ClubId { get; set; }
        [ForeignKey("ClubId")]
        [Display(Name = "CLB")]
        public Clubs Clubs { get; set; }
        [Required]
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
    }
}

HCM/Areas/Admin/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClubManagement.Models;
using HCM.Data;

namespace HCM.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MembersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Members
        public async Task<IActionResult> Index(int id)
        {
            var id2 = id > 0 ? id : -1;
            var club = _context.Clubs.ToList();
            ViewBag.ListByClub = club;
            var applicationDbContext = _context.Members.Include(m => m.Clubs);

            if (id2 != -1)
            {
                return View(await applicationDbContext.Where(m => m.ClubId == id2).ToListAsync());
            }

                
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .Include(m => m.Clubs)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // GET: Admin/Members/Create
        public IActionResult Create()
        {
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name");
            return View();
        }

        // POST: Admin/Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,StudentNumber,Password,Email,PhoneNumber,IsAccecpt,ClubId,Description")] Members members)
        {
            if (ModelState.IsValid)
            {
                _context.Add(members);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // GET: Admin/Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members.FindAsync(id);
            if (members == null)
            {
                return NotFound();
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // POST: Admin/Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,StudentNumber,Password,Email,PhoneNumber,IsAccecpt,ClubId,Description")] Members members)
        {
            if (id != members.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(members);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembersExists(members.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // GET: Admin/Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .Include(m => m.Clubs)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // POST: Admin/Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var members = await _context.Members.FindAsync(id);
            _context.Members.Remove(members);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembersExists(int id)
        {
            return _context.Members.Any(e => e.Id == id);
        }
    }
}

HCM/Areas/Member/Controllers/HomeController.cs
using HCM.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HCM.Areas.Member.Controllers
{
    [Area("Member")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.TotalClub = _context.Clubs.Count();
            ViewBag.TotalLocation = _context.Locations.Count();
            ViewBag.TotalMember = _context.Members.Count();
            ViewBag.TotalSchedule = _context.Schedules.Count();
            return View();
        }
    }
}

HCM/Areas/Member/Controllers/LoginController.cs
using HCM.Data;
using HCM.Extensions;
using HCM.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HCM.Areas.Member.Controllers
{
    [Area("Member")]
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoginController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string StudentNumber, string password)
        {
            ViewBag.error = "";
            var at = _context.Members.ToList();
            var data = _context.Members.Where(p => p.StudentNumber == StudentNumber && p.Password == password).ToList();
            if (data.Count() > 0)
            {
                List<Login> member = new List<Login>();
                member.Add(new Login { members = at.Find(p => p.StudentNumber == StudentNumber) });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "Login", member);
                return RedirectToAction("Index", "Schedules");
            }

            else
            {
                ViewBag.error = "Đăng nhập thất bại";
                return View("Index");

            }
        }

        public IActionResult Logout()
        {

            SessionHelper.GetObjectFromJson<List<Login>>(HttpContext.Session, "Login").Clear();
            List<Login> member = new List<Login>();
            SessionHelper.SetObjectAsJson(HttpContext.Session, "Login", member);
            return RedirectToAction("Index");
        }
    }
}

HCM/Areas/Member/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClubManagement.Models;
using HCM.Data;

namespace HCM.Areas.Member.Controllers
{
    [Area("Member")]
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MembersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Member/Members
        public async Task<IActionResult> Index(int id)
        {
            var id2 = id > 0 ? id : -1;
            var club = _context.Clubs.ToList();
            ViewBag.ListByClub = club;
            var applicationDbContext = _context.Members.Include(m => m.Clubs);

            if (id2 != -1)
            {
                return View(await applicationDbContext.Where(m => m.ClubId == id2).ToListAsync());
            }


            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Member/Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .Include(m => m.Clubs)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // GET: Member/Members/Create
        public IActionResult Create()
        {
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name");
            return View();
        }

        // POST: Member/Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,StudentNumber,Password,Email,PhoneNumber,IsAccecpt,ClubId,Description")] Members members)
        {
            if (ModelState.IsValid)
            {
                _context.Add(members);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // GET: Member/Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members.FindAsync(id);
            if (members == null)
            {
                return NotFound();
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // POST: Member/Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,StudentNumber,Password,Email,PhoneNumber,IsAccecpt,ClubId,Description")] Members members)
        {
            if (id != members.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(members);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembersExists(members.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClubId"] = new SelectList(_context.Clubs, "Id", "Name", members.ClubId);
            return View(members);
        }

        // GET: Member/Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .Include(m => m.Clubs)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // POST: Member/Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var members = await _context.Members.FindAsync(id);
            _context.Members.Remove(members);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembersExists(int id)
        {
            return _context.Members.Any(e => e.Id == id);
        }
    }
}

HCM/Areas/Member/Controllers/SchedulesController.cs
using HCM.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HCM.Areas.Member.Controllers
{
    [Area("Member")]
    public class SchedulesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SchedulesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("event/Find")]
        public IActionResult FindAllEvents()
        {
            var events = _context.Schedules.Select(e => new
            {
                id = e.Id,
                title = e.Clubs.Name + " - " + e.Location,
                description = e.Description,
                start = e.StartDate,
                end = e.EndDate,
                club = e.Clubs.Name,

                
            }).ToList();

            return new JsonResult(events);
        }
    }
}

HCM/Areas/Member/Views/Members/Create.cshtml
@model ClubManagement.Models.Members

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Member.cshtml";
}

<h1>Create</h1>

<h4>Members</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentNumber" class="control-label"></label>
                <input asp-for="StudentNumber" class="form-control" />
                <span asp-validation-for="StudentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAccecpt" /> @Html.DisplayNameFor(model => model.IsAccecpt)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ClubId" class="control-label"></label>
                <select asp-for="ClubId" class ="form-control" asp-items="ViewBag.ClubId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HCM/Areas/Member/Views/Members/Delete.cshtml
@model ClubManagement.Models.Members

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Member.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Members</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAccecpt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAccecpt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clubs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clubs.ClubDetails)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HCM/Areas/Member/Views/Members/Details.cshtml
@model ClubManagement.Models.Members

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Member.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Members</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAccecpt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAccecpt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clubs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clubs.ClubDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HCM/Areas/Member/Views/Members/Index.cshtml
@model IEnumerable<ClubManagement.Models.Members>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Member.cshtml";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thành viên</h1>
                <br />
                <a class="btn btn-primary" asp-action="Create"><i class="fa fa-plus" aria-hidden="true"></i> Thêm mới</a>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Members</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- /.card -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Dữ liệu từ bảng Members</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FullName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.StudentNumber)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PhoneNumber)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IsAccecpt)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Clubs)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FullName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IsAccecpt)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Clubs.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                     
                                            <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Chi tiết</a>
                                  
                                        </td>
                                    </tr>
                                }

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <div class="btn-group dropright">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Chọn CLB
                    </button>
                    <div class="dropdown-menu">
                        <!-- Dropdown menu links -->
                        @foreach (var item in ViewBag.ListByClub)
                        {

                            <p class="dropdown-item">
                                @Html.ActionLink((string)item.Name, "Index", "Members", new { id = item.Id })
                            </p>

                        }
                    </div>
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>

<script>
    $(function () {
        $("#example1").DataTable({
            lengthMenu: [
                [3, 10, 15, -1],
                [3, 10, 15, 'All'],
            ],
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
</script>