HCM/Models/Clubs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ClubManagement.Models
{
    public class Clubs
    {
        public int Id { get; set; }
        [Required]
        [Display(Name="CLB")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Tên đăng nhập")]
        public string Username { get; set; }
        //[StringLength(18, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        //[RegularExpression(@"^((?=.*[a-z])(?=.*[A-Z])(?=.*\d)).+$")]
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu")]
        [Required]
        public string Password { get; set; }
        [Display(Name = "Ngày tạo")]
        public DateTime CreateAt { get; set; }
        [Required]
        [Display(Name = "Giờ sinh hoạt")]
        public string Time { get; set; }
        [Display(Name = "Ảnh")]
        public string Image { get; set; }
        [Display(Name = "Mô tả")]
        [Required]
        public string Description { get; set; }
        [Display(Name = "Yêu cầu")]
        [Required]
        public string Require { get; set; }
        [Display(Name = "Chi tiết")]
        [Required]
        public string ClubDetails { get; set; }
        [Display(Name = "Địa điểm")]
        public int LocationId { get; set; }
        [ForeignKey("LocationId")]
        public Locations Locations { get; set; }
        [Display(Name = "Người tạo")]
        public int ManagerId { get; set; }
        [ForeignKey("ManagerId")]
        [Display(Name = "Người tạo")]
        public Managers Managers { get; set; }
    }
}

HCM/Areas/Admin/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClubManagement.Models;
using HCM.Data;

namespace HCM.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ClubsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClubsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Clubs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Clubs.Include(c => c.Locations).Include(c => c.Managers);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Clubs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs
                .Include(c => c.Locations)
                .Include(c => c.Managers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clubs == null)
            {
                return NotFound();
            }

            return View(clubs);
        }

        // GET: Admin/Clubs/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name");
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email");
            return View();
        }

        // POST: Admin/Clubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Username,Password,CreateAt,Time,Image,Description,Require,ClubDetails,LocationId,ManagerId")] Clubs clubs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clubs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // GET: Admin/Clubs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs.FindAsync(id);
            if (clubs == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // POST: Admin/Clubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Username,Password,CreateAt,Time,Image,Description,Require,ClubDetails,LocationId,ManagerId")] Clubs clubs)
        {
            if (id != clubs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clubs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClubsExists(clubs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // GET: Admin/Clubs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs
                .Include(c => c.Locations)
                .Include(c => c.Managers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clubs == null)
            {
                return NotFound();
            }

            return View(clubs);
        }

        // POST: Admin/Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clubs = await _context.Clubs.FindAsync(id);
            _context.Clubs.Remove(clubs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClubsExists(int id)
        {
            return _context.Clubs.Any(e => e.Id == id);
        }
    }
}

HCM/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClubManagement.Models;
using HCM.Data;

namespace HCM.Controllers
{
    public class ClubsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClubsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clubs
        public async Task<IActionResult> Index(int id)
        {
            var id2 = id > 0 ? id : -1;
            var location = _context.Locations.ToList();
            ViewBag.ListByLocation = location;

            var applicationDbContext = _context.Clubs.Include(c => c.Locations).Include(c => c.Managers);
            if (id2 != -1)
            {
                return View(await applicationDbContext.Where(m => m.LocationId == id2).ToListAsync());
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Clubs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs
                .Include(c => c.Locations)
                .Include(c => c.Managers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clubs == null)
            {
                return NotFound();
            }

            return View(clubs);
        }

        // GET: Clubs/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name");
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email");
            return View();
        }

        // POST: Clubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Username,Password,CreateAt,Time,Image,Description,Require,ClubDetails,LocationId,ManagerId")] Clubs clubs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clubs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // GET: Clubs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs.FindAsync(id);
            if (clubs == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // POST: Clubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Username,Password,CreateAt,Time,Image,Description,Require,ClubDetails,LocationId,ManagerId")] Clubs clubs)
        {
            if (id != clubs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clubs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClubsExists(clubs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", clubs.LocationId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Email", clubs.ManagerId);
            return View(clubs);
        }

        // GET: Clubs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clubs = await _context.Clubs
                .Include(c => c.Locations)
                .Include(c => c.Managers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clubs == null)
            {
                return NotFound();
            }

            return View(clubs);
        }

        // POST: Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clubs = await _context.Clubs.FindAsync(id);
            _context.Clubs.Remove(clubs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClubsExists(int id)
        {
            return _context.Clubs.Any(e => e.Id == id);
        }
    }
}

HCM/Views/Clubs/Details.cshtml
@model ClubManagement.Models.Clubs

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_User.cshtml";
}


<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Chi tiết CLB</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb text-uppercase">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item"><a href="#">CLB</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Chi tiết CLB</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Header End -->
<!-- Job Detail Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="row gy-5 gx-4">
            <div class="col-lg-8">
                <div class="d-flex align-items-center mb-5">
                    <img class="flex-shrink-0 img-fluid" src="https://cdn.haitrieu.com/wp-content/uploads/2021/09/Logo-DH-CONG-NGHE-THANH-PHO-HO-CHI-MINH-HUTECH.png" alt="" style="width: 80px; height: 80px;">
                    <div class="text-start ps-4">
                        <h3 class="mb-3">@Html.DisplayFor(model => model.Name)</h3>
                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>@Html.DisplayFor(model => model.Locations.Name)</span>
                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>@Html.DisplayFor(model => model.Time)</span>
                    </div>
                </div>

                <div class="mb-5">
                    <h4 class="mb-3">Mô tả</h4>
                    <p>@Html.DisplayFor(model => model.Description)</p>
                    <h4 class="mb-3">Yêu cầu</h4>
                    <p>@Html.DisplayFor(model => model.Require)</p>
                    <h4 class="mb-3">Khác</h4>
                    <p>@Html.DisplayFor(model => model.ClubDetails)</p>
                </div>


                
            </div>

            <div class="col-lg-4">
                <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                    <h4 class="mb-4">Tóm tắt</h4>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Ngày tạo: @Html.DisplayFor(model => model.CreateAt)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Địa điểm: @Html.DisplayFor(model => model.Locations.Name)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Thời gian: @Html.DisplayFor(model => model.Time)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Người tạo: @Html.DisplayFor(model => model.Managers.FullName)</p>
                </div>
                <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                    <h4 class="mb-4">Chi tiết CLB</h4>
                    <p class="m-0">@Html.DisplayFor(model => model.ClubDetails)</p>
                </div>
            </div>
        </div>
    </div>
</div>

HCM/Views/Clubs/Index.cshtml
@model IEnumerable<ClubManagement.Models.Clubs>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_User.cshtml";
}

<div class="container-xxl py-5 bg-dark page-header mb-5" style="background: linear-gradient(rgba(43, 57, 64, .5), rgba(43, 57, 64, .5)), url(https://media-cdn-v2.laodong.vn/storage/newsportal/2022/9/12/1091965/Dh-Cong-Nghe-Hutech.jpg) center center repeat ">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Câu lạc bộ</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb text-uppercase">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item"><a href="#">CLB</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Danh sách CLB</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Header End -->
<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Danh sách CLB</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                @foreach (var item in ViewBag.ListByLocation)
                {
                    <li class="nav-item">
                        <p class="d-flex align-items-center text-start mx-3 ms-0 pb-3" data-bs-toggle="pill" href="#tab-1">
                            @Html.ActionLink((string)item.Name, "Index", "Clubs", new { id = item.Id }, new { style = "text-decoration: none; font-weight: bold; color: black" })
                            @*<a style="text-decoration: none; font-weight: bold; color: black" href="@Url.Action( * "Index", "Clubs", new { id = item.Id })"></a>*@
                        </p>
                    </li>
                }

                
            </ul>
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    @foreach (var item in Model)
                    {
                        <div class="job-item p-4 mb-4">
                            <div class="row g-4">
                                <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                    <img class="flex-shrink-0 img-fluid" src="https://cdn.haitrieu.com/wp-content/uploads/2021/09/Logo-DH-CONG-NGHE-THANH-PHO-HO-CHI-MINH-HUTECH.png" alt="" style="width: 80px; height: 80px;">
                                    <div class="text-start ps-4">
                                        <h5 class="mb-3">@Html.DisplayFor(modelItem => item.Name)</h5>
                                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>@Html.DisplayFor(modelItem => item.Locations.Name)</span>
                                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>@Html.DisplayFor(modelItem => item.Time)</span>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                    <div class="d-flex mb-3">
                                        <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                        <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Tham gia</a>
                                    </div>
                                    <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Ngày tạo: @Html.DisplayFor(modelItem => item.CreateAt)</small>
                                </div>
                            </div>
                        </div>
                    }



                    <a class="btn btn-primary py-3 px-5" href="">Xem thêm CLB</a>
                </div>
            </div>
        </div>
    </div>
</div>